server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/arknights
    driver-class-name: org.postgresql.Driver
    username: ${USER}

spring.sql.init.mode: always

logging.level.org.springframework.web: DEBUG
logging.level.org.springdoc: DEBUG
